-- Future Supabase schema draft
create table if not exists events (id uuid primary key default gen_random_uuid(), name text not null, venue text, starts_at timestamptz, status text default 'draft');
create table if not exists participants (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, full_name text not null, email text, phone text, ticket_number text, avatar_url text, quiz_score integer default 0, created_at timestamptz default now());
create table if not exists speakers (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, full_name text not null, title text, avatar_url text, created_at timestamptz default now());
create table if not exists quiz_questions (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, question text not null, options jsonb not null, correct_index integer not null, time_limit integer default 15, sort_order integer default 0);
create table if not exists quiz_answers (id uuid primary key default gen_random_uuid(), question_id uuid references quiz_questions(id) on delete cascade, participant_id uuid references participants(id) on delete cascade, selected_index integer, is_correct boolean, response_ms integer, created_at timestamptz default now());
create table if not exists raffle_entries (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, participant_id uuid references participants(id) on delete cascade, ticket_number text not null, created_at timestamptz default now());
create table if not exists raffle_draws (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, prize_name text not null, participant_id uuid references participants(id), ticket_number text, drawn_at timestamptz default now());
create table if not exists questions (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, participant_id uuid references participants(id), speaker_id uuid references speakers(id), body text not null, status text default 'pending', created_at timestamptz default now(), answered_at timestamptz);
