const state={view:"dashboard",quizIndex:0,score:0,timer:null,timeLeft:15,quizRunning:false,tickets:231,questions:12,participants:[["001","Nathalie Kasongo","nathalie@example.com","#014","82%","Actif"],["002","Kevin Ilunga","kevin@example.com","#117","74%","Actif"],["003","Grâce Mbala","grace@example.com","#084","91%","Actif"],["004","Fabrice Mbuyi","fabrice@example.com","#203","67%","Actif"],["005","Amina Kabeya","amina@example.com","#056","88%","Actif"],["006","Patrick Lufungula","patrick@example.com","#161","—","Actif"]],speakers:[["AM","Aïcha Mukendi","Stratégie & Innovation","8 questions"],["JM","Jean-Marc Banza","Transformation digitale","11 questions"],["NK","Nadia Kanku","CX & Marketing","15 questions"],["PD","Paul Dibwe","Leadership","3 questions"]]};
const quiz=[{q:"Quel est le meilleur usage de l’IA générative dans une expérience client ?",a:["Répondre plus vite aux demandes répétitives","Remplacer toute l’équipe","Supprimer les données","Bloquer les retours"],c:0},{q:"Quel indicateur mesure le mieux l’engagement pendant un événement ?",a:["Nombre de slides","Temps de parole","Taux de participation","Taille de la salle"],c:2},{q:"À quoi sert un QR code dans cette expérience ?",a:["Changer les lumières","Accéder rapidement au formulaire","Augmenter le son","Créer un badge physique"],c:1},{q:"Que doit faire un modérateur avant d’afficher une question ?",a:["La supprimer","La valider et l’orienter","Changer le nom","L’envoyer à tous"],c:1},{q:"Pourquoi utiliser une tombola numérique ?",a:["Créer une attente visible et auditable","Éviter les participants","Supprimer les lots","Remplacer les intervenants"],c:0}];
const questions=[["Q-034","Nathalie Kasongo","Aïcha Mukendi","Comment mesurez-vous le ROI d’une transformation digitale ?","2 min","pending"],["Q-033","Kevin Ilunga","Jean-Marc Banza","Quelle place donnez-vous aux équipes métiers dans le déploiement ?","4 min","pending"],["Q-032","Grâce Mbala","Nadia Kanku","Quels signaux indiquent qu’un parcours client doit être repensé ?","7 min","ready"],["Q-031","Amina Kabeya","Aïcha Mukendi","Comment éviter que l’IA rende les parcours trop impersonnels ?","9 min","ready"],["Q-030","Patrick Lufungula","Paul Dibwe","Quel rôle le leadership joue-t-il dans l’adoption ?","12 min","ready"]];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)}
function switchView(v){state.view=v;$$(".view").forEach(x=>x.classList.remove("active-view"));$("#view-"+v).classList.add("active-view");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#pageTitle").textContent={dashboard:"Dashboard",quiz:"Quiz live",raffle:"Tombola",qa:"Questions / Réponses",people:"Participants",speakers:"Intervenants"}[v];window.scrollTo({top:0,behavior:"smooth"})}
$$(".nav-item").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));$$("[data-go]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.go)));
function renderQuiz(){const q=quiz[state.quizIndex];$("#quizProgress").textContent=`QUESTION ${state.quizIndex+1} / ${quiz.length}`;$("#quizQuestion").textContent=q.q;$("#answers").innerHTML=q.a.map((x,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(65+i)} · ${x}</button>`).join("");$("#quizScore").textContent=`Score : ${state.score}`;$$(".answer").forEach(b=>b.onclick=()=>answerQuiz(+b.dataset.i));}
function resetTimer(){clearInterval(state.timer);state.timeLeft=15;$("#timer").textContent=15}
function startQuiz(){if(state.quizRunning)return;state.quizRunning=true;state.quizIndex=0;state.score=0;renderQuiz();$("#quizStatus").textContent="Quiz en cours…";runTimer()}
function runTimer(){resetTimer();state.timer=setInterval(()=>{state.timeLeft--;$("#timer").textContent=state.timeLeft;if(state.timeLeft<=0){clearInterval(state.timer);lockQuestion() }},1000)}
function lockQuestion(){state.quizRunning=false;$$(".answer").forEach(b=>b.disabled=true);$("#quizStatus").textContent="Temps écoulé !";setTimeout(nextQuestion,900)}
function answerQuiz(i){if(!state.quizRunning)return;clearInterval(state.timer);state.quizRunning=false;const q=quiz[state.quizIndex];$$(".answer").forEach(b=>b.disabled=true);const buttons=$$(".answer");buttons[q.c].classList.add("correct");if(i===q.c){state.score++;$("#quizStatus").textContent="Bonne réponse +1";}else{buttons[i].classList.add("wrong");$("#quizStatus").textContent="Pas cette fois";}$("#quizScore").textContent=`Score : ${state.score}`;setTimeout(nextQuestion,900)}
function nextQuestion(){state.quizIndex++;if(state.quizIndex>=quiz.length){$("#quizStatus").textContent=`Quiz terminé · ${state.score}/${quiz.length}`;$("#timer").textContent="✓";return}renderQuiz();state.quizRunning=true;runTimer()}
$("#startQuiz").onclick=startQuiz;$("#resetQuiz").onclick=()=>{state.quizRunning=false;clearInterval(state.timer);state.quizIndex=0;state.score=0;renderQuiz();$("#quizStatus").textContent="Prêt à lancer";resetTimer()};renderQuiz();
const raffleNames=[["Nathalie Kasongo","#014"],["Kevin Ilunga","#117"],["Grâce Mbala","#084"],["Fabrice Mbuyi","#203"],["Amina Kabeya","#056"],["Patrick Lufungula","#161"],["Chantal Moke","#092"],["Blaise Kanku","#175"]];
function draw(){const btn=$("#drawWinner");btn.disabled=true;let n=0;const iv=setInterval(()=>{const p=raffleNames[Math.floor(Math.random()*raffleNames.length)];$("#shuffleNumber").textContent=p[1];$("#shuffleName").textContent=p[0];$("#drawStatus").textContent="Tirage en cours…";n++;if(n>22){clearInterval(iv);const w=raffleNames[Math.floor(Math.random()*raffleNames.length)];$("#shuffleNumber").textContent=w[1];$("#shuffleName").textContent=w[0];$("#drawStatus").textContent="🎉 Gagnant sélectionné";$("#winnerPhoto").textContent="★";$("#winnerHistory").insertAdjacentHTML("afterbegin",`<div><span>${w[1]}</span><strong>${w[0]}</strong><small>Grand tirage · maintenant</small></div>`);btn.disabled=false;toast(`Gagnant : ${w[0]} ${w[1]}`) }},80)}
$("#drawWinner").onclick=draw;$("#addTicket").onclick=()=>{state.tickets++;$("#drawStatus").textContent=`${state.tickets} tickets participants`;toast("Inscription simulée ajoutée")};
function renderQA(){$("#questionsList").innerHTML=questions.map((q,i)=>`<div class="question-item ${q[5]==="pending"?"pending":""}"><div class="question-meta"><span>${q[0]} · ${q[1]}</span><span>${q[4]}</span></div><p>${q[3]}</p><div class="question-actions"><button onclick="approveQ(${i})">✓ Afficher</button><button onclick="dismissQ(${i})">Masquer</button></div></div>`).join("");$("#qaHeadline").textContent=`${state.questions} questions`};window.approveQ=i=>{questions[i][5]="ready";state.questions=Math.max(0,state.questions-1);renderQA();toast("Question approuvée pour le live")};window.dismissQ=i=>{questions.splice(i,1);state.questions=Math.max(0,state.questions-1);renderQA();toast("Question retirée de la file")};renderQA();
function renderSpeakers(){const markup=state.speakers.map(s=>`<div class="speaker"><div class="speaker-avatar">${s[0]}</div><div><strong>${s[1]}</strong><span>${s[2]}</span></div></div>`).join("");$("#speakerList").innerHTML=markup;$("#speakerCards").innerHTML=state.speakers.map(s=>`<article class="speaker-card"><div class="speaker-card-top"><div class="speaker-avatar">${s[0]}</div><div><h3>${s[1]}</h3><p>${s[2]}</p></div></div><div class="speaker-stat"><span>Questions reçues</span><b>${s[3]}</b></div></article>`).join("")};renderSpeakers();
function renderPeople(){$("#peopleTable").innerHTML=state.participants.map(p=>`<tr><td>${p[0]}</td><td><strong>${p[1]}</strong></td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td><span class="status">${p[5]}</span></td></tr>`).join("")};renderPeople();
function addSpeaker(){const s=[String.fromCharCode(65+state.speakers.length)+"S","Nouvel intervenant","À configurer","0 questions"];state.speakers.push(s);renderSpeakers();toast("Intervenant ajouté")};$("#addSpeaker").onclick=addSpeaker;$("#addSpeaker2").onclick=addSpeaker;
$("#openQr").onclick=()=>$("#qrModal").classList.add("open");$("#closeQr").onclick=()=>$("#qrModal").classList.remove("open");$("#qrModal").addEventListener("click",e=>{if(e.target.id==="qrModal")e.currentTarget.classList.remove("open")});$("#fullscreenBtn").onclick=()=>document.documentElement.requestFullscreen?.();$("#themeBtn").onclick=()=>document.body.classList.toggle("light");$("#exportPeople").onclick=()=>{const csv=[["ID","Participant","Email","Ticket","Quiz","Statut"],...state.participants].map(r=>r.join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="participants-btl.csv";a.click();toast("CSV exporté")};